### PR TITLE
badger api: update to v1.5.0

### LINKED ISSUE #1: Update Badger tests
I would like to use Tove to test Badger's latest version v1.5.0.

From what I'm seeing in the [`util`](https://github.com/dgraph-io/tove/blob/a9db6103db075e7be356560eeea38f9c0c8ee9d0/badger/util/util.go) package and the errors from running the [`run.sh`](https://github.com/dgraph-io/tove/blob/a9db6103db075e7be356560eeea38f9c0c8ee9d0/badger/run.sh) script this test should be updated to use Badger's transaction API and also the recently modified GC API.

```
# github.com/dgraph-io/tove/badger/util
util/util.go:12:21: undefined: badger.KV
util/util.go:25:5: opt.ValueGCRunInterval undefined (type *badger.Options has no field or method ValueGCRunInterval)
util/util.go:26:5: opt.ValueGCThreshold undefined (type *badger.Options has no field or method ValueGCThreshold)
util/util.go:30:13: undefined: badger.NewKV
util/util.go:46:17: undefined: badger.KV
util/util.go:52:18: undefined: badger.KV
util/util.go:52:40: undefined: badger.KVItem
util/util.go:53:14: undefined: badger.KVItem
util/util.go:64:22: undefined: badger.KV
```

@manishrjain @peterstace Any other modifications I should consider?

### PR DESCRIPTION
**Pull request by schomatis**
* Update the tests to use the Badger transactions API to get/set/delete.

* Removed Badger automatic GC options as Badger now requires to trigger
  a manual GC, a new test will need to be added for that.

* Removed `MaxTableSize` option as it was causing an `ErrTxnTooBig`
  for any single `txn.Set()` operation.

Closes #1.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/tove/2)

### CODE REVIEW

**Comment by schomatis** [comment]
@manishrjain Could you please check the rest of the [options](https://github.com/dgraph-io/tove/pull/2/files#diff-419285a7ecbecf8ae99afa17e74d0ad9R12) previously used here to see if they still make sense for the current Badger version?

**Comment by manishrjain** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[badger/util/util.go, line 12 at r1](https://reviewable.io/reviews/dgraph-io/tove/2#-LCWKk7Q9XcEMtgjZDAz:-LCWKk7Q9XcEMtgjZDB-:b-nsmgln) ([raw file](https://github.com/dgraph-io/tove/blob/7d65e5bfe2a74816604462a20dd4fb41cdd0387c/badger/util/util.go#L12)):*
> ```Go
> func StartBadger() *badger.DB {
> 	opt := badger.DefaultOptions
> 	opt.NumLevelZeroTables = 1
> ```

Why remove MaxTableSize?

---

*[badger/util/util.go, line 17 at r1](https://reviewable.io/reviews/dgraph-io/tove/2#-LCWKzYpA6oCilvDYaSv:-LCWKzYpA6oCilvDYaSw:b-mui51o) ([raw file](https://github.com/dgraph-io/tove/blob/7d65e5bfe2a74816604462a20dd4fb41cdd0387c/badger/util/util.go#L17)):*
> ```Go
> 	opt.LevelOneSize = 2 << 20
> 	opt.ValueLogFileSize = 5 << 20
> 	opt.SyncWrites = false
> ```

Note that SyncWrites must be true for valid results. I think Peter might have switched this around for some extra testing for async writes.

---

*[badger/util/util.go, line 19 at r1](https://reviewable.io/reviews/dgraph-io/tove/2#-LCWKPjS1knQ7P_Y_OZq:-LCWKPjS1knQ7P_Y_OZr:b62n260) ([raw file](https://github.com/dgraph-io/tove/blob/7d65e5bfe2a74816604462a20dd4fb41cdd0387c/badger/util/util.go#L19)):*
> ```Go
> 	opt.SyncWrites = false
> 
> 	opt.Dir = "."
> ```

You need to now explicitly call Value Log GC, to make the GC happen, passing in a similar threshold. In fact, based on the options here, it looks like there always was GC going on, all the time (with a millisecond pause in between).

---

*[badger/util/util.go, line 58 at r1](https://reviewable.io/reviews/dgraph-io/tove/2#-LCWJo4j72X4jDZ-BiWt:-LCWJo4j72X4jDZ-BiWu:b-akxolh) ([raw file](https://github.com/dgraph-io/tove/blob/7d65e5bfe2a74816604462a20dd4fb41cdd0387c/badger/util/util.go#L58)):*
> ```Go
> 		}
> 
> 		_, err = item.ValueCopy(value)
> ```

value, err = item.ValueCopy(value)

Otherwise, if a new slice is allocated, you won't pick it up.

---

*[badger/util/util.go, line 89 at r1](https://reviewable.io/reviews/dgraph-io/tove/2#-LCWK5x3Aov_61mb-BpC:-LCWK5x3Aov_61mb-BpD:bo5v9yo) ([raw file](https://github.com/dgraph-io/tove/blob/7d65e5bfe2a74816604462a20dd4fb41cdd0387c/badger/util/util.go#L89)):*
> ```Go
> func KeyHasValue(kv *badger.DB, k, v []byte) bool {
> 	Assert(Exists(kv, k))
> 	value := MustGet(kv, k)
> ```

The get can now return ErrKeyNotFound, which it didn't before. So, based on usage, this might or might not be OK. Something to consider.

---

*[badger/workload/workload.go, line 45 at r1](https://reviewable.io/reviews/dgraph-io/tove/2#-LCWKHkE0YQIG4unHbt2:-LCWKHkF3KMePjdIonZk:b-vr1iqe) ([raw file](https://github.com/dgraph-io/tove/blob/7d65e5bfe2a74816604462a20dd4fb41cdd0387c/badger/workload/workload.go#L45)):*
> ```Go
> 	fmt.Println("start:set-key")
> 	kv := StartBadger()
> 	MustSet(kv, k1, v1)
> ```

I'd recommend renaming all `kv`s to `db`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/dgraph-io/tove/2)*

**Comment by schomatis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[badger/util/util.go, line 12 at r1](https://reviewable.io/reviews/dgraph-io/tove/2#-LCWKk7Q9XcEMtgjZDAz:-LCYjZ2e5kdvxSH8cvrj:b947t5i) ([raw file](https://github.com/dgraph-io/tove/blob/7d65e5bfe2a74816604462a20dd4fb41cdd0387c/badger/util/util.go#L12)):*
> * Removed `MaxTableSize` option as it was causing an `ErrTxnTooBig`
>   for any single `txn.Set()` operation.

---

*[badger/util/util.go, line 17 at r1](https://reviewable.io/reviews/dgraph-io/tove/2#-LCWKzYpA6oCilvDYaSv:-LCYjq854wpogyGguDsW:bxxx4gf) ([raw file](https://github.com/dgraph-io/tove/blob/7d65e5bfe2a74816604462a20dd4fb41cdd0387c/badger/util/util.go#L17)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Note that SyncWrites must be true for valid results. I think Peter might have switched this around for some extra testing for async writes.
</blockquote></details>

That makes sense.

---

*[badger/util/util.go, line 19 at r1](https://reviewable.io/reviews/dgraph-io/tove/2#-LCWKPjS1knQ7P_Y_OZq:-LCYk0kzBs-IQqvkq_v1:ba7yq48) ([raw file](https://github.com/dgraph-io/tove/blob/7d65e5bfe2a74816604462a20dd4fb41cdd0387c/badger/util/util.go#L19)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You need to now explicitly call Value Log GC, to make the GC happen, passing in a similar threshold. In fact, based on the options here, it looks like there always was GC going on, all the time (with a millisecond pause in between).
</blockquote></details>

Yes, see commit message. This will have to be handled in a separate test. Some conditions will have to be met so when calling Value Log GC it actually triggers a rewrite in the value log.

---

*[badger/util/util.go, line 58 at r1](https://reviewable.io/reviews/dgraph-io/tove/2#-LCWJo4j72X4jDZ-BiWt:-LCYksLf6ImC24z6msL1:b-896fix) ([raw file](https://github.com/dgraph-io/tove/blob/7d65e5bfe2a74816604462a20dd4fb41cdd0387c/badger/util/util.go#L58)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

value, err = item.ValueCopy(value)

Otherwise, if a new slice is allocated, you won't pick it up.
</blockquote></details>

Done.

---

*[badger/util/util.go, line 89 at r1](https://reviewable.io/reviews/dgraph-io/tove/2#-LCWK5x3Aov_61mb-BpC:-LCYl7TF7MKOCwpCe7up:br6b3fx) ([raw file](https://github.com/dgraph-io/tove/blob/7d65e5bfe2a74816604462a20dd4fb41cdd0387c/badger/util/util.go#L89)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

The get can now return ErrKeyNotFound, which it didn't before. So, based on usage, this might or might not be OK. Something to consider.
</blockquote></details>

If `txn.Get()` returns `ErrKeyNotFound` the `Must` in `MustGet` will end the test with `log.Fatal`.

---

*[badger/workload/workload.go, line 45 at r1](https://reviewable.io/reviews/dgraph-io/tove/2#-LCWKHkE0YQIG4unHbt2:-LCYlf7x6VsV4qQFAQbt:b-pbdqz3) ([raw file](https://github.com/dgraph-io/tove/blob/7d65e5bfe2a74816604462a20dd4fb41cdd0387c/badger/workload/workload.go#L45)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

I'd recommend renaming all `kv`s to `db`.
</blockquote></details>

Agreed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/dgraph-io/tove/2)*

**Comment by schomatis** [comment]
@manishrjain Thanks for the comprehensive review.

**Comment by manishrjain** [comment]
:lgtm: Few more comments, but looks good mostly.

I'll give you write access to this repo. So, you can merge when you deem fit. However, do send code reviews for future updates too.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[badger/util/util.go, line 12 at r1](https://reviewable.io/reviews/dgraph-io/tove/2#-LCWKk7Q9XcEMtgjZDAz:-LCaAKFd7pFUO7Af8c9Z:bspt11r) ([raw file](https://github.com/dgraph-io/tove/blob/7d65e5bfe2a74816604462a20dd4fb41cdd0387c/badger/util/util.go#L12)):*
<details><summary><i>Previously, schomatis (Lucas Molas) wrote…</i></summary><blockquote>

> * Removed `MaxTableSize` option as it was causing an `ErrTxnTooBig`
>   for any single `txn.Set()` operation.

</blockquote></details>

You still might want to bring it back (increase the limit a bit), otherwise, your testing would get really hard. ALICE is slow, because it has to compute all permutations -- so running too long to fill up one SSTable won't work out.

---

*[badger/util/util.go, line 19 at r1](https://reviewable.io/reviews/dgraph-io/tove/2#-LCWKPjS1knQ7P_Y_OZq:-LCaA_ZB4aeFmvNkvKRV:bswwufs) ([raw file](https://github.com/dgraph-io/tove/blob/7d65e5bfe2a74816604462a20dd4fb41cdd0387c/badger/util/util.go#L19)):*
<details><summary><i>Previously, schomatis (Lucas Molas) wrote…</i></summary><blockquote>

Yes, see commit message. This will have to be handled in a separate test. Some conditions will have to be met so when calling Value Log GC it actually triggers a rewrite in the value log.
</blockquote></details>

The value log threshold of 0.001 should trigger a rewrite (almost) always.

---

*[badger/util/util.go, line 89 at r1](https://reviewable.io/reviews/dgraph-io/tove/2#-LCWK5x3Aov_61mb-BpC:-LCaAih0-AwlC7H7mGwq:b-rq6cxz) ([raw file](https://github.com/dgraph-io/tove/blob/7d65e5bfe2a74816604462a20dd4fb41cdd0387c/badger/util/util.go#L89)):*
<details><summary><i>Previously, schomatis (Lucas Molas) wrote…</i></summary><blockquote>

If `txn.Get()` returns `ErrKeyNotFound` the `Must` in `MustGet` will end the test with `log.Fatal`.
</blockquote></details>

OK. And you might want to avoid that crash. Not sure. Depends upon what this test expects to see. Anyway, if you see unexpected crashes, it might be because of this.

---


*Comments from [Reviewable](https://reviewable.io/reviews/dgraph-io/tove/2#-:-LCaAzfc8Y36WJsdxpDy:b-uwh1vf)*

**Comment by schomatis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[badger/util/util.go, line 12 at r1](https://reviewable.io/reviews/dgraph-io/tove/2#-LCWKk7Q9XcEMtgjZDAz:-LCdBTm_31S70a118xTI:b-qfbxhd) ([raw file](https://github.com/dgraph-io/tove/blob/7d65e5bfe2a74816604462a20dd4fb41cdd0387c/badger/util/util.go#L12)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

You still might want to bring it back (increase the limit a bit), otherwise, your testing would get really hard. ALICE is slow, because it has to compute all permutations -- so running too long to fill up one SSTable won't work out.
</blockquote></details>

Ok, setting it to 2K then.

---

*[badger/util/util.go, line 19 at r1](https://reviewable.io/reviews/dgraph-io/tove/2#-LCWKPjS1knQ7P_Y_OZq:-LCdBhdDE6HRvDItwNgM:b-619snf) ([raw file](https://github.com/dgraph-io/tove/blob/7d65e5bfe2a74816604462a20dd4fb41cdd0387c/badger/util/util.go#L19)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

The value log threshold of 0.001 should trigger a rewrite (almost) always.
</blockquote></details>

I see, but `ValueGCThreshold` is no longer available at the options level, my understanding is that this option is now `discardRatio` of `RunValueLogGC`, so I'll have it under consideration for the GC tests.

---


*Comments from [Reviewable](https://reviewable.io/reviews/dgraph-io/tove/2)*

**Pull request merged**
