### PR TITLE
Enable truncation

### PR DESCRIPTION
**Pull request by schomatis**
Fixes the vulnerabilities found in https://github.com/dgraph-io/badger/issues/489.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/tove/3)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[badger/util/util.go, line 21 at r1](https://reviewable.io/reviews/dgraph-io/tove/3#-LCjN7oL-5XuXivcG1fN:-LCjN7oL-5XuXivcG1fO:bhulkup) ([raw file](https://github.com/dgraph-io/tove/blob/4f8cecaaafd13264683a6e9ad44804663af5fac0/badger/util/util.go#L21)):*
> ```Go
> 	// Allow truncation, the objective of theses tests is not to avoid
> 	// data loss in case of corrupted appends, but rather to test for
> 	// atomicity in those appends maintaining the DB integrity.
> ```

The comment can be misleading. I don't think you can achieve atomic appends via Badger. Atomic appends depend upon the file system, whether it supports them or not.

---


*Comments from [Reviewable](https://reviewable.io/reviews/dgraph-io/tove/3)*

**Comment by schomatis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[badger/util/util.go, line 21 at r1](https://reviewable.io/reviews/dgraph-io/tove/3#-LCjN7oL-5XuXivcG1fN:-LCjRW7H45o647ODs1_0:b3k2sbc) ([raw file](https://github.com/dgraph-io/tove/blob/4f8cecaaafd13264683a6e9ad44804663af5fac0/badger/util/util.go#L21)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

The comment can be misleading. I don't think you can achieve atomic appends via Badger. Atomic appends depend upon the file system, whether it supports them or not.
</blockquote></details>

I've meant appends at the Badger level, not the file system. As discussed in a Badger [issue](https://github.com/dgraph-io/badger/issues/489#issuecomment-389662221) file system appends (and other write-related operations) may not be atomic, but it is expected that Badger's operations are, either the key is added/updated/removed or it is not, but any intermediary steps should not be possible (as Badger would detect them upon replay and discard them). Help me phrase this better, should I replace "append" with "Badger operation"? How would you put it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/dgraph-io/tove/3)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[badger/util/util.go, line 21 at r1](https://reviewable.io/reviews/dgraph-io/tove/3#-LCjN7oL-5XuXivcG1fN:-LCjTp7V5EHS825V5039:b-j2lght) ([raw file](https://github.com/dgraph-io/tove/blob/4f8cecaaafd13264683a6e9ad44804663af5fac0/badger/util/util.go#L21)):*
<details><summary><i>Previously, schomatis (Lucas Molas) wrote…</i></summary><blockquote>

I've meant appends at the Badger level, not the file system. As discussed in a Badger [issue](https://github.com/dgraph-io/badger/issues/489#issuecomment-389662221) file system appends (and other write-related operations) may not be atomic, but it is expected that Badger's operations are, either the key is added/updated/removed or it is not, but any intermediary steps should not be possible (as Badger would detect them upon replay and discard them). Help me phrase this better, should I replace "append" with "Badger operation"? How would you put it?
</blockquote></details>

Badger is already transaction. You'd either see your whole transaction or not. So, say a file write leaves garbage data in value log (this happens before a txn is considered committed), due to process crash or something. When the value log replay would happen, the checksum would not match, and those entries would be discarded.

Alternatively, the process crashes after the writes were successfully done in value log. Then a replay would pick those up, and make them part of the LSM tree, to be found by other transactions.

Again, I think those issues that you're chasing, are just artifacts of the file system quirks picked up by Trove. Trove doesn't know the internal structure of Badger, and how it works.

---


*Comments from [Reviewable](https://reviewable.io/reviews/dgraph-io/tove/3)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[badger/util/util.go, line 21 at r1](https://reviewable.io/reviews/dgraph-io/tove/3#-LCjN7oL-5XuXivcG1fN:-LCjsVAZ0kqJ6ytpvsz1:byhzldz) ([raw file](https://github.com/dgraph-io/tove/blob/4f8cecaaafd13264683a6e9ad44804663af5fac0/badger/util/util.go#L21)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Badger is already transaction. You'd either see your whole transaction or not. So, say a file write leaves garbage data in value log (this happens before a txn is considered committed), due to process crash or something. When the value log replay would happen, the checksum would not match, and those entries would be discarded.

Alternatively, the process crashes after the writes were successfully done in value log. Then a replay would pick those up, and make them part of the LSM tree, to be found by other transactions.

Again, I think those issues that you're chasing, are just artifacts of the file system quirks picked up by Trove. Trove doesn't know the internal structure of Badger, and how it works.
</blockquote></details>

I'd word the comment as:

// Allow truncation because ALICE would add garbage data to the value log.

---


*Comments from [Reviewable](https://reviewable.io/reviews/dgraph-io/tove/3)*

**Comment by schomatis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[badger/util/util.go, line 21 at r1](https://reviewable.io/reviews/dgraph-io/tove/3#-LCjN7oL-5XuXivcG1fN:-LCjVjur4zZDEbvbjd8w:bg08ktn) ([raw file](https://github.com/dgraph-io/tove/blob/4f8cecaaafd13264683a6e9ad44804663af5fac0/badger/util/util.go#L21)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

I'd word the comment as:

// Allow truncation because ALICE would add garbage data to the value log.
</blockquote></details>

Thanks for answering the original question, I'll reword like that then.

---


*Comments from [Reviewable](https://reviewable.io/reviews/dgraph-io/tove/3)*

**Comment by manishrjain** [comment]
Thanks, Lucas!

**Pull request merged**
